all: findfreesubnet subaddrnum2cidr
clean:
	rm -rf findfreesubnet subaddrnum2cidr
findfreesubnet: findfreesubnet.c
	cc findfreesubnet.c -o findfreesubnet
subaddrnum2cidr: subaddrnum2cidr.c
	cc subaddrnum2cidr.c -o subaddrnum2cidr
